//
// Created by Markus Kannisto on 10/03/2022.
//

#pragma once

enum TokenType {
    ROOT,
    OPEN_PARENTHESES,
    CLOSE_PARENTHESES,
    NAME,
    INTEGER_LITERAL,
    STRING_LITERAL,
    CHARACTER_LITERAL,
    BOOLEAN_LITERAL,
    FLOAT_LITERAL,
    STATEMENT_TERMINATOR,
    POINT,
    OPEN_BRACES,
    CLOSE_BRACES,
    STATEMENT_IDENTIFIER,
    KEYWORD,
    RETURN_STATEMENT,
    ADDITION_OPERATOR,
    OPEN_BRACKETS,
    CLOSE_BRACKETS,
    BRACKETS,
    EQUALITY_OPERATOR,
    ASSIGNMENT_OPERATOR,
    ADDITION_ASSIGNMENT_OPERATOR,
    INCREMENT_OPERATOR,
    SUBTRACTION_OPERATOR,
    SUBTRACTION_ASSIGNMENT_OPERATOR,
    DECREMENT_OPERATOR,
    MULTIPLICATION_ASSIGNMENT_OPERATOR,
    MULTIPLICATION_OPERATOR,
    DIVISION_ASSIGNMENT_OPERATOR,
    DIVISION_OPERATOR,
    LOGICAL_AND_OPERATOR,
    LOGICAL_OR_OPERATOR,
    LOGICAL_NOT_OPERATOR,
    LOGICAL_LESS_THAN_OPERATOR,
    LOGICAL_MORE_THAN_OPERATOR,
    COLON,
    COMMA,
    IDENTIFIER,
    PARAMETER_PACK,
    OPERATOR,
    NULL_VALUE,

    EXPRESSION,
    STATEMENT_BODY,

    C_STATEMENT
};
